### ISSUE TITLE
Improve on or incorporate component contribution

### ISSUE THREAD

**Issue by teddygroves** [biosustain/Maud#188]

**Comment by teddygroves** [comment]
I spent a lot of time on this! Long story short, it is definitely possible to improve on component contribution, but it is a pretty big project that is outside the scope of Maud. 

I think the best we can do in Maud is to let the user optionally specify a multivariate prior for the vector of formation energies. This should allow us to capture the available thermodynamic information no matter what method we use upstream.

**Comment by Midnighter** [comment]
Hi @teddygroves, I'm not sure what sort of improvements you had in mind but there are a number of changes coming pretty soon that might be helpful.

1. I recently added a function to automatically map cobra metabolites and reactions to equilibrator ones.
2. Elad and Vishnu are working on improvements to the covariance matrix.
3. Then there's the work Vishnu is doing that may or may not be helpful in your case.
