### ISSUE TITLE
Ignore parts of the model which are not required

### ISSUE THREAD

**Issue by denisshepelin** [biosustain/Maud#196]
I'm constructing a model from parts - 
Model specific
1) backbone that specifies what reactions are there
2) metabolomics+fluxomics measurements 
3) unbalanced metabolites priors
4) enzyme abundance priors

The last two are constant between models and I want to reuse them. 
5) marginal dGs 
6) kinetic parameters of enzymes 

`maud sample` will fail currently with error like this if I specify prior for reactions which is not existing in the model. :

```
ValueError: kinetic parameter FBP_Kcat1 has a prior but is not in the kinetic model.
```

I would like to be able to put some additional information in the model files without it failing.

**Comment by teddygroves** [comment]
I think we should now be able to this handle this use case using the knockout feature.
