### ISSUE TITLE
Pre-flight check for vmaxes

### ISSUE THREAD

**Issue by teddygroves** [biosustain/Maud#232]
Before Maud starts sampling it should report the 95% prior quantile of vmax (i.e. enzyme concentration times kcat) for each reaction. This should show if the priors make it impossible for the network to carry enough flux. This should be possible to calculate analytically.

**Comment by NicholasCowie** [comment]
I don't think there's a clear cut way to implement this analytically. Using the prior predictive check to identify if the priors contain the measurements is a more thorough workflow.
