### ISSUE TITLE
Implement drains

### ISSUE THREAD

**Issue by teddygroves** [biosustain/Maud#243]
Options:
1. Michaelis Menten with a constant on the other side
2. Irreversible mass action
3. Constant drains

Options 1 and 2 have a problem: it's quite hard to force the drain to be constant using these mechanisms.

The other option is setting drains as constant. This leads to the problem of enzymes that don't carry flux that is high enough to match the drain.

We need a case study documenting how we deal with drains and exploring all these options.

**Comment by NicholasCowie** [comment]
Drains work well although ODE solver requires tweaking occasionally to a higher tolerance. This is a simple issue to fix yet I would suggest the more relaxed parameters as default
