### ISSUE TITLE
Feature Checking

### ISSUE THREAD

**Issue by NicholasCowie** [biosustain/Maud#287]
# Purpose
To validate the features currently implemented in Maud from the viewpoint of being able to recover a defined parameter set.

# Method
1. Develop a model for each feature,
2. Define parameter set,
3. Simulate model with parameter set,
4. Prior predictive check on model,
5. Sample model using measured data,
6. Check that model is correct,
7. Investigate algorithm behaviour (divergences, funnels, correlation, etc.).

## List of models
- [ ] Standard Model
- [ ] Drains
- [ ] Phosphorylation
- [ ] Allostery
- [ ] Isoenzymes

**Comment by NicholasCowie** [comment]
* Included tests in the `integration_tests` folder,
* New model files,
* True parameter sets included in jsons,
* Use case study function in scripts to automate steps 3-6,
* Include simulation results at the end of corresponding rst file for each feature.

**Comment by teddygroves** [comment]
I'm going to start by making the case study function and adding an integration test that calls it, using the existing `linear.toml` file as input

**Comment by NicholasCowie** [comment]
Using the `linear.toml` I'm going to remove all regulation and attempt to find ideal number of experiments to recover the true paraemeters

**Comment by NicholasCowie** [comment]
1. Generate TOML files with measurements of conc/flux. Given plausible parameters
2. Can include noise, but not essential
