### ISSUE TITLE
Bug: can't differentiate between allosteric activators or inhibitors via allostery ID

### ISSUE THREAD

**Issue by NicholasCowie** [biosustain/Maud#397]
Need to include another field called regulation type in the input files

**Comment by teddygroves** [comment]
I think this isn't necessary as I think we would never have two allosteries with the same enzyme and mic but different modification types, and adding the extra field to the id would require adding lots of blanks to every priors csv file.

**Comment by NicholasCowie** [comment]
I like that implementation. Unfortunately, there are instances I’ve observed where at different concentrations metabolites can be both inhibitors and activators.

**Comment by teddygroves** [comment]
OK, looks like I didn't waste that works then!
