### ISSUE TITLE
Experimentally observed Vmax's

### ISSUE THREAD

**Issue by NicholasCowie** [biosustain/Maud#64]
When a paper gives results in flux through different isoenzymes without accounting for enzyme concentration. Rather than placing priors on the ratio of $k_{cat}$'s. place the prior on the ratio's  of Vmax's. e.g. Vmax_A/Vmax_B = (kcat_A/kcat_B)*(E_A/E_B)

**Only Applicable when testing conditions are the same as litereature**

**Comment by teddygroves** [comment]
I think this doesn't fit into the current framework
